/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-09-12 05:46:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1535186006182L));
    _jspx_dependants.put("jar:file:/D:/bhavin/work_space/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/acitivity-portal/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>Home</title>\n");
      out.write("\t\n");
      out.write("  <style>\n");
      out.write("      body {\n");
      out.write("          text-align: center;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      section {\n");
      out.write("          width: 81%;\n");
      out.write("          margin: auto;\n");
      out.write("          text-align: left;\n");
      out.write("      }\n");
      out.write("  </style>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0\"/>\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/froala_editor.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/froala_style.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/code_view.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/colors.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/draggable.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/emoticons.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/image_manager.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/image.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/line_breaker.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/table.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/char_counter.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/video.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/fullscreen.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/file.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/plugins/quick_insert.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.css\">\n");
      out.write("  \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<section id=\"editor\">\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/save-question\" id=\"fileUploadForm\" method=\"post\">\n");
      out.write("    \n");
      out.write("    \t<h1>Admin Form</h1>\n");
      out.write("\n");
      out.write("\tActivity Name<input type=\"text\"  name=\"activity_name\" id=\"activity_name\"><br>\n");
      out.write("\tHow To play <textarea rows=\"2\" cols=\"2\" name=\"tip\" id=\"tip\"></textarea><br>\n");
      out.write("\tHint<input type=\"text\"  name=\"hint\" id=\"hint\">\n");
      out.write("\tActivity Type<select name=\"activity_type\" id=\"activity_type\">\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</select>\n");
      out.write("\tTemplate:<select name=\"template\" id=\"template\">\n");
      out.write("\t\t\t\t<option value=\"template1\">Template 1</option>\n");
      out.write("\t\t\t\t<option>Template 2</option>\n");
      out.write("\t\t\t\t<option>Template 3</option>\n");
      out.write("\t\t\t\t<option>Template 4</option>\n");
      out.write("\t\t\t\t<option>Template 5</option>\n");
      out.write("\t\t\t\t<option>Template 6</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\n");
      out.write("<!--     Option1<input type=\"checkbox\" name=\"ans\" value=\"1\" /> \n");
      out.write("        Option2<input type=\"checkbox\" name=\"ans\" value=\"2\" /> \n");
      out.write("            Option3<input type=\"checkbox\" name=\"ans\" value=\"3\" /> \n");
      out.write("                Option4<input type=\"checkbox\" name=\"ans\" value=\"4\" />  -->\n");
      out.write("\n");
      out.write("      Question:<div id='question' style=\"margin-top: 30px;\">\n");
      out.write("    </div>\n");
      out.write("\t<div id=\"option_section\">\n");
      out.write("\t\n");
      out.write("\t</div>\n");
      out.write("  <!--   Option 1<div id='opt1' style=\"margin-top: 30px;\">\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    Option 2<div id='opt2' style=\"margin-top: 30px;\">\n");
      out.write("    </div>\n");
      out.write("    Option 3<div id='opt3' style=\"margin-top: 30px;\">\n");
      out.write("    </div>\n");
      out.write("     Option 4<div id='opt4' style=\"margin-top: 30px;\">\n");
      out.write("    </div> -->\n");
      out.write("    <input type=\"button\" value=\"Save\" id=\"save-activity\">\n");
      out.write("    </form>\n");
      out.write("  </section>\n");
      out.write("  \n");
      out.write("  <div>\n");
      out.write("  \t<button id=\"add_option\">Add Option</button>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/mode/xml/xml.min.js\"></script>\n");
      out.write("\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/froala_editor.min.js\" ></script>\n");
      out.write("\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/align.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/code_beautifier.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/code_view.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/colors.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/draggable.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/emoticons.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/font_size.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/font_family.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/image.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/file.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/image_manager.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/line_breaker.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/link.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/lists.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/paragraph_format.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/paragraph_style.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/video.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/table.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/url.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/entities.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/char_counter.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/inline_style.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/save.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/fullscreen.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/quote.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/quick_insert.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"https://editor-latest.s3.amazonaws.com/js/third_party/image_aviary.min.js\"></script>\n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("  $(function(){\n");
      out.write("      var options=[];\n");
      out.write("   \t  var index=0;\n");
      out.write("   \t  \n");
      out.write("\t  $('#question').froalaEditor({\n");
      out.write("    \t  imageUploadParam: 'file',\n");
      out.write("   \t //     initOnClick: true,\n");
      out.write("   // \t  imageUploadURL: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/upload_image-base',\n");
      out.write("      }).on('froalaEditor.image.beforeUpload', function (e, editor, files) {\n");
      out.write("          if (files.length) {\n");
      out.write("              var reader = new FileReader();\n");
      out.write("              reader.onload = function (e) {\n");
      out.write("                 var result = e.target.result;\n");
      out.write("                 editor.image.insert(result, null, null, editor.image.get());\n");
      out.write("              };\n");
      out.write("              reader.readAsDataURL(files[0]);\n");
      out.write("            }\n");
      out.write("            editor.popups.hideAll();\n");
      out.write("            \n");
      out.write("            return false;\n");
      out.write("          });\n");
      out.write("      \n");
      out.write("      $('#add_option').click(function(){\n");
      out.write("    \t  \n");
      out.write("    \t\tindex++;  \n");
      out.write("          \t$('#option_section').append('option'+index+'<input type=\"checkbox\" name=\"ans\" value=\"'+index+'\" /><div id=\"opt'+index+'\" style=\"margin-top: 30px;\">');\n");
      out.write("          \t\n");
      out.write("          \tif (!$('#opt'+index).data('froala.editor')) {\n");
      out.write("          \t      $('#opt'+index).froalaEditor().on('froalaEditor.image.beforeUpload', function (e, editor, files) {\n");
      out.write("          \t          if (files.length) {\n");
      out.write("         \t              var reader = new FileReader();\n");
      out.write("\t          \t          reader.onload = function (e) {\n");
      out.write("         \t                  var result = e.target.result;\n");
      out.write("          \t                  editor.image.insert(result, null, null, editor.image.get());\n");
      out.write("          \t              };\n");
      out.write("          \t              reader.readAsDataURL(files[0]);\n");
      out.write("          \t            }\n");
      out.write("          \t            editor.popups.hideAll();\n");
      out.write("          \t            return false;\n");
      out.write("          \t          });\n");
      out.write("          \t      ;\n");
      out.write("          \t    }\n");
      out.write("          //\t$('#opt'+index).editable(\"setHTML\", \"<p></p>\", false);\n");
      out.write("      \n");
      out.write("      });\n");
      out.write("\t  $('#save-activity').click(function(){\n");
      out.write("\t\t\n");
      out.write("\t\t var data = new FormData();\n");
      out.write("\t\t  data.append(\"activity_name\",  $('#activity_name').val());\n");
      out.write("\t\t  data.append(\"hint\",  $('#hint').val());\n");
      out.write("\t\t  data.append(\"activity_type\",  $('#activity_type').val());\n");
      out.write("\t\t  data.append(\"template\",$('#template').val() );\n");
      out.write("\t\t  data.append(\"ans\", $('#opt'+$('input[type=\"checkbox\"]:checked').val()).froalaEditor('html.get'));\n");
      out.write("\t\t  data.append(\"tip\", $('#tip').val());\n");
      out.write("\t\t  data.append(\"question\",$('#question').froalaEditor('html.get') );\n");
      out.write("\t\t  for(var i=1;i<=index;i++){\n");
      out.write("\t\t\t  data.append(\"opt\"+i, $('#opt'+i).froalaEditor('html.get'));\n");
      out.write("\t\t  }\t \n");
      out.write("\t\t  \n");
      out.write("\t\t  /* {\n");
      out.write("\t\t\t   \"activity_name\": $('#activity_name').val(),\n");
      out.write("\t\t\t   \"hint\": $('#hint').val(),\n");
      out.write("\t\t\t   \"activity_type\": $('#activity_type').val(),\n");
      out.write("\t\t\t   \"template\": $('#template').val(),\n");
      out.write("\t\t\t   \"ans\": $('#opt'+$('input[type=\"checkbox\"]:checked').val()).froalaEditor('html.get'),\n");
      out.write("\t\t\t   \"tip\": $('#tip').val(),\n");
      out.write("\t\t\t   \"question\": $('#question').froalaEditor('html.get'),\n");
      out.write("\t\t\t /*   \"opt1\": $('#opt1').froalaEditor('html.get'),\n");
      out.write("\t\t\t   \"opt2\": $('#opt2').froalaEditor('html.get'),\n");
      out.write("\t\t\t   \"opt3\": $('#opt3').froalaEditor('html.get'),\n");
      out.write("\t\t\t   \"opt4\": $('#opt4').froalaEditor('html.get') \n");
      out.write("\t\t   } */\n");
      out.write("\t\t  $.ajax({\n");
      out.write("\t\t\t   url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/save-question',\n");
      out.write("\t\t\t   type: 'post',\n");
      out.write("\t\t\t   processData: false,\n");
      out.write("\t\t\t   contentType: false,\n");
      out.write("\t\t\t   data:data/*  {\n");
      out.write("\t\t\t\t   \"activity_name\": $('#activity_name').val(),\n");
      out.write("\t\t\t\t   \"hint\": $('#hint').val(),\n");
      out.write("\t\t\t\t   \"activity_type\": $('#activity_type').val(),\n");
      out.write("\t\t\t\t   \"template\": $('#template').val(),\n");
      out.write("\t\t\t\t   \"ans\": $('#opt'+$('input[type=\"checkbox\"]:checked').val()).froalaEditor('html.get'),\n");
      out.write("\t\t\t\t   \"tip\": $('#tip').val(),\n");
      out.write("\t\t\t\t   \"question\": $('#question').froalaEditor('html.get'),\n");
      out.write("\t\t\t\t   \"opt1\": $('#opt1').froalaEditor('html.get'),\n");
      out.write("\t\t\t\t   \"opt2\": $('#opt2').froalaEditor('html.get'),\n");
      out.write("\t\t\t\t   \"opt3\": $('#opt3').froalaEditor('html.get'),\n");
      out.write("\t\t\t\t   \"opt4\": $('#opt4').froalaEditor('html.get') \n");
      out.write("\t\t\t   } */,\n");
      out.write("\t\t\t   error: function() {\n");
      out.write("\t\t\t      alert(\"errop\")\n");
      out.write("\t\t\t   },\n");
      out.write("\t\t\t  success: function(data) {\n");
      out.write("\t\t\t     alert(data)\n");
      out.write("\t\t\t   }\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t});\n");
      out.write("\t  }) \n");
      out.write("\n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/home.jsp(50,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("activityType");
    // /WEB-INF/views/home.jsp(50,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(50,2) '${activityTypes}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${activityTypes}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activityType.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activityType.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\t\t\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
